steps:
  # Build the container image and push it with Kaniko
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --cache=true
      - --destination=gcr.io/$PROJECT_ID/quarkus-multistage
      - --build-arg=MY_SECRET
    timeout: 1200s
    secretEnv: ['MY_SECRET']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'quarkus-multistage'
      - '--image'
      - 'gcr.io/$PROJECT_ID/quarkus-multistage:latest'
      - '--region'
      - 'europe-north1'
      - '--platform'
      - 'managed'
timeout: 1200s
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/MY_SECRET/versions/latest
      env: 'MY_SECRET'